# Example solve input for `end-cli`.
# Modify this file for your own use.
#
# Units:
# - power: watts (W)
# - item flows: units per minute
# - money cap: per hour

version = 2

region = "wuling"

[power]
enabled = true
# External stable generation not modeled by thermal-bank fuel loops.
# Defaults to 200W (core power).
external_production = 200
# External stable consumption from non-production systems.
external_consumption = 800

[objective]
max_money_slack = 1.0

# External item supply per minute.
[supply_per_min]
"item_originium_ore" = 540
"item_originium_enr_powder" = 25
"item_copper_ore" = 420
"item_iron_ore" = 120
"item_gas_inert" = 120
"item_gas_xiranite" = 100


# External item consumption per minute.
# e.g. Consumables, Delivery
[external_consumption_per_min]
"item_equip_script_4_3" = 1
"item_gas_acid" = 6

[facility_machines_max]
"xiranite_oven_1" = 12


[[outposts]]
# Unique identifier.
key = "tianwang"
# Max revenue accepted by this outpost per hour.
money_cap_per_hour = 42000
# Display name (Optional).
en = "天王坪"
zh = "天王坪"

# Item -> price
[outposts.prices]
"item_proc_battery_5" = 54
"item_copper_enr2_cmpt" = 70
"item_copper_enr_cmpt" = 48
"item_xiranite_enr_powder" = 27
"item_bottled_rec_hp_5" = 22

[[outposts]]
# Unique identifier.
key = "shoudun"
# Max revenue accepted by this outpost per hour.
money_cap_per_hour = 27360
# Display name (Optional).
en = "心脏修缮站"
zh = "心脏修缮站"

# Item -> price
[outposts.prices]
"item_proc_battery_5" = 54
"item_copper_enr2_cmpt" = 70
"item_copper_enr_cmpt" = 48
"item_xiranite_enr_powder" = 27
"item_bottled_rec_hp_5" = 22

[[outposts]]
# Unique identifier.
key = "yinglong"
# Max revenue accepted by this outpost per hour.
money_cap_per_hour = 19440
# Display name (Optional).
en = "盈天台"
zh = "盈天台"

# Item -> price
[outposts.prices]
"item_proc_battery_5" = 54
"item_copper_enr2_cmpt" = 70
"item_copper_enr_cmpt" = 48
"item_xiranite_enr_powder" = 27
"item_bottled_rec_hp_5" = 22
